project:
  type: website
  # output-dir: docs

website:
  title: "Ecoinform치tica-AEET"
  twitter-card: true
  site-url: https://ecoinfaeet.github.io/
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: miembros.qmd
        text: Miembros
      - href: notas-ecoinformaticas.qmd
        text: Notas Ecoinform치ticas
      - href: seminarios.qmd
        text: Seminarios
      - text: Actividades
        menu:
          - text: "I Jornadas de Ecoinform치tica"
            href: jornadas.qmd
          - text: "AEET 2023"
            href: activ_AEET2023.qmd
          - text: "AEET 2021"
            href: activ_AEET2021.qmd
          - text: "MEDECOS 2017"
            href: activ_medecos2017.qmd
          - text: "MEDECOS 2017 - Symposium"
            href: activ_symposium_2017.qmd
      - text: Recursos
        menu:
          - text: "Reproducibilidad"
            href: activ_reproducibilidad.qmd
  search: 
    location: navbar
    type: textbox
  page-footer: 
    center: 
      - icon: twitter
        href: https://twitter.com/ecoinf_aeet
      - href: https://ecoinfaeet.github.io/website/
        text: Ecoinform치tica-AEET
      - icon: github
        href: https://github.com/ecoinfAEET
    background: rgba(51,153,103,255)

format:
  html:
    link-external-newwindow: true
    theme: minty
    css: styles.css
    toc: true
    linkcolor: rebeccapurple
    page-layout: full

execute:
  freeze: auto
